from django.db import models

# Create your models here.
class savedMovie(models.Model):
    userid = models.IntegerField(null=False)
    imdbid = models.IntegerField(null=False)
    title = models.CharField(max_length=50, null=False)
    year = models.IntegerField()
    rating = models.CharField(max_length=8)
    release = models.CharField(max_length=15)
    runtime = models.CharField(max_length=8)
    genre = models.CharField(max_length=50)
    director = models.CharField(max_length=25)
    writer = models.CharField(max_length=35)
    actors = models.CharField(max_length=50)
    plot = models.CharField(max_length=100)
    language = models.CharField(max_length=50)
    country = models.CharField(max_length=20)
    awards = models.CharField(max_length=50)
    poster = models.CharField(max_length=200)
    ratings = models.CharField(max_length=200)
    metascore = models.CharField(max_length=4)
    imdbRating = models.CharField(max_length=4)
    imdbVotes = models.CharField(max_length=10)
    type = models.CharField(max_length=8)
    DVD = models.CharField(max_length=15)
    boxoffice = models.CharField(max_length=15)
    production = models.CharField(max_length=15)
    website = models.CharField(max_length=50)
    response = models.BooleanField()