# Generated by Django 3.2.15 on 2022-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('imdbid', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rating', models.CharField(max_length=8)),
                ('release', models.CharField(max_length=15)),
                ('runtime', models.CharField(max_length=8)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=25)),
                ('writer', models.CharField(max_length=35)),
                ('actors', models.CharField(max_length=50)),
                ('plot', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('awards', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('metascore', models.CharField(max_length=4)),
                ('imdbRating', models.CharField(max_length=4)),
                ('imdbVotes', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=8)),
                ('DVD', models.CharField(max_length=15)),
                ('boxoffice', models.CharField(max_length=15)),
                ('production', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('response', models.BooleanField()),
            ],
        ),
    ]
